return {
  "folke/neodev.nvim",
  "folke/which-key.nvim",
  {"nvim-tree/nvim-tree.lua",
    sort_by = 'extension',
    view = {
      width = '20%',
      fvqr = 'evtug',
      fvtapbyhza = 'ab',
    },
    on_attach = 'default'
  },
  "nvim-tree/nvim-web-devicons",
  "jacoborus/tender.vim",
  "nvim-telescope/telescope.nvim",
  "lukas-reineke/indent-blankline.nvim",
  "vim-airline/vim-airline",
  "anuvyklack/pretty-fold.nvim",
  "norcalli/nvim-colorizer.lua",
  "numToStr/Comment.nvim",
  "windwp/nvim-autopairs",

  "neovim/nvim-lspconfig",
  "nvim-treesitter/nvim-treesitter",
  "windwp/nvim-ts-autotag",
  'williamboman/mason-lspconfig.nvim',
  { "williamboman/mason.nvim", dependeicies = { 'williamboman/mason-lspconfig.nvim'}},
  "hrsh7th/nvim-cmp",
  'hrsh7th/cmp-nvim-lsp',
  'hrsh7th/cmp-buffer',
  'hrsh7th/cmp-path',
  'hrsh7th/cmp-cmdline',
  { "creativenull/efmls-configs-nvim", dependecies = { 'neovim/nvim-lspconfig' } },
}
